version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.3
    commands:
      - echo "Installing system dependencies..."
      - apt update && apt install -y unzip curl git nginx
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
  pre_build:
    commands:
      - echo "Setting up Laravel environment..."
      - composer install --no-dev --prefer-dist --optimize-autoloader

  build:
    commands:
      - echo "Configuring Permission"
      - chmod -R 775 storage bootstrap/cache
      - chown -R www-data:www-data .
      - echo "Creating artifact..."
      - zip -r ../laravel-app.zip .

  post_build:
    commands:
      - echo "Build completed."

artifacts:
  files:
    - ../laravel-app.zip
  discard-paths: yes
  name: laravel-app-${CODEBUILD_BUILD_NUMBER}

